name: ygg_pomodoro
description: "Pomodoro Application"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  dio: ^5.1.0
  url_launcher: ^6.1.6
  http: ^1.0.0
  flutter_html: ^3.0.0-beta.2
  app_links: ^6.3.3
  fluent_ui: ^4.9.2
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  youtube_player_flutter: ^9.1.1
  mesh_gradient: ^1.3.8
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
